// Auto-generated by export_js.py — do not edit manually
// This is placeholder data. Run `python3 run_pipeline.py --domain energy` to generate real data.
const THEMES_DATA = {
  "generated_at": "2026-04-15T00:00:00",
  "total_themes": 0,
  "total_source_items": 0,
  "themes": []
};
