#!/usr/bin/env python3
"""
Export themes data as a JavaScript file for the GitHub Pages dashboard.
"""

import json
from pathlib import Path

DATA_THEMES = Path(__file__).parent.parent / "data" / "themes"
OUTPUT_JS = Path(__file__).parent.parent / "themes_data.js"


def run():
    """Export latest.json as themes_data.js for the frontend."""
    latest = DATA_THEMES / "latest.json"
    if not latest.exists():
        print("エラー: data/themes/latest.json がありません。先に aggregate.py を実行してください。")
        return

    with open(latest, encoding="utf-8") as f:
        data = json.load(f)

    js_content = f"// Auto-generated by export_js.py — do not edit manually\nconst THEMES_DATA = {json.dumps(data, ensure_ascii=False, indent=2)};\n"

    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"  Exported to {OUTPUT_JS} ({OUTPUT_JS.stat().st_size:,} bytes)")


if __name__ == "__main__":
    run()
